# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyliwc',
                'doc_host': 'https://camille1.github.io',
                'git_url': 'https://github.com/camille1/pyliwc',
                'lib_path': 'pyliwc'},
  'syms': {'pyliwc.core': {'pyliwc.core.foo': ('core.html#foo', 'pyliwc/core.py')}}}
