# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['liwc']

# %% ../nbs/00_core.ipynb 3
def liwc(): 
    "Say hello to somebody"
    import pandas as pd
    print("camille liwc")
    print(pd.__version__)
    print("camille liwc")
