# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_process.ipynb.

# %% auto 0
__all__ = ['foo', 'liwc']

# %% ../nbs/01_process.ipynb 3
def foo(): 
    print(pd.__version__)
    pass

# %% ../nbs/01_process.ipynb 4
def liwc(): 
    print("camille liwc")
    pass
