# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_process.ipynb.

# %% auto 0
__all__ = ['l']

# %% ../nbs/01_process.ipynb 3
import pandas as pd
def l(): 
    print("camille liwc")
    print(pd.__version__)
    pass
